baseURL = "https://onwardauditing.com"
title = "Onward Auditing"
author = "onward"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['services']

  [params.logo]
    main = "img/logo/logo_horizontal.png"
    alt = "Onward Auditing Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.recaptcha]
    siteKey = "6LeAO0YfAAAAAC30dY1oPQcGN3VPQfnvRetThEsd"

  [params.site]
    name = "Onward Auditing"
    addressStreet = "825 Town & Country Ln"
    addressStreet2 = "Suite 1200"
    addressCity = "Houston"
    addressState = "TX"
    addressZip = "77024"
    addressUrl = "https://goo.gl/maps/skr32DXz61MS7soT7"
    phone = "281-535-CREW (2739)"

  [params.icon]
    fa5 = true

  [params.homepage_meta_tags]
    meta_description = "Onward Auditing"
    meta_og_title = "Onward Auditing"
    meta_og_type = "website"
    meta_og_url = "https://onwardauditing.com"
    meta_og_image = "/img/screenshot.png"
    meta_og_description = "Onward Auditing"
    #meta_twitter_card = "summary_large_image"
    #meta_twitter_site = "@username"
    #meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 3

  [[menu.main]]
    identifier = "policies"
    name = "Policies"
    url = "/policies/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Onward Inc"
    url = "https://crewonward.com"
    weight = 1

  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/onwardllc"
    pre = "<i class='fab fa-linkedin fa-2xl'></i>"
    weight = 2

  [[menu.footer]]
    name = "Facebook"
    url = "https://www.facebook.com/onwardconsultingincorporated/"
    pre = "<i class='fab fa-facebook fa-2xl'></i>"
    weight = 3
