name: deploy

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - run: npm ci
      - run: hugo --minify

      - name: update production branch
        uses: actions/github-script@v8
        env:
          SHA: ${{ github.sha }}
          AUTHOR: ${{ github.actor }}
          EMAIL: ${{ github.actor }}@users.noreply.github.com
        with:
          script: |
            git checkout target-branch
            git checkout source-branch -- public
            mv public/* .
            rm -rf public
            git add .
            git commit --author="${AUTHOR} <${EMAIL}>" -m "Deploy: ${SHA}"
            git push origin production
