name: github pages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - run: npm ci
      - run: hugo --minify

      - name: build gh-pages branch
        uses: peaceiris/actions-gh-pages@v4 # v4 # (latest, tagged)
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
