name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@6b42224f41ee5dfe5395e27c8b2746f1f9955030 # v4 # (latest, tagged)
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@3b443076f02aa9537a31bdcaa0c971cdd41eb022 # v3  # (latest, tagged)
        with:
          hugo-version: 'latest'
          extended: true

      - name: setup node
        uses: actions/setup-node@aca7b64a59c0063db8564e0ffdadd3887f1cbae5 # v4 # (latest, tagged)
        with:
          node-version: '20'

      - run: npm ci
      - run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@ababa3d330af34b07419f6bc9f4a6b817ed7930b # v4 # (latest, tagged)
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
